name: 'retail'
version: '1.0'
profile: 'retail'
require-dbt-version: [">=1.3.0", "<2.0.0"]
config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"

models:
  retail:
    materialized: table
